#
# TABLE STRUCTURE FOR: country
#

DROP TABLE IF EXISTS `country`;

CREATE TABLE `country` (
  `CountryID` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(255) NOT NULL,
  PRIMARY KEY (`CountryID`)
) ENGINE=InnoDB AUTO_INCREMENT=196 DEFAULT CHARSET=latin1;

INSERT INTO `country` (`CountryID`, `Name`) VALUES (1, 'Poland');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (2, 'Suriname');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (3, 'Greece');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (4, 'Central African Republic');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (5, 'Malaysia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (6, 'Kuwait');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (7, 'Uzbekistan');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (8, 'Cayman Islands');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (9, 'American Samoa');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (10, 'British Indian Ocean Territory (Chagos Archipelago)');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (11, 'Togo');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (12, 'Iran');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (13, 'Netherlands');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (14, 'Djibouti');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (15, 'Trinidad and Tobago');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (16, 'Sierra Leone');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (17, 'Lebanon');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (18, 'Finland');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (19, 'Uganda');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (20, 'El Salvador');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (21, 'Heard Island and McDonald Islands');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (22, 'Faroe Islands');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (23, 'Cambodia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (24, 'Nicaragua');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (25, 'Chile');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (26, 'Cape Verde');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (27, 'Liechtenstein');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (28, 'Turks and Caicos Islands');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (29, 'Tajikistan');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (30, 'Luxembourg');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (31, 'Timor-Leste');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (32, 'South Georgia and the South Sandwich Islands');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (33, 'Bosnia and Herzegovina');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (34, 'Indonesia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (35, 'Brazil');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (36, 'Seychelles');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (37, 'Saint Vincent and the Grenadines');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (38, 'Nauru');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (39, 'Christmas Island');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (40, 'Slovakia (Slovak Republic)');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (41, 'United States of America');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (42, 'Canada');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (43, 'Montserrat');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (44, 'Anguilla');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (45, 'Palestinian Territory');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (46, 'Tonga');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (47, 'Estonia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (48, 'South Africa');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (49, 'France');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (50, 'Libyan Arab Jamahiriya');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (51, 'Yemen');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (52, 'Belize');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (53, 'United Kingdom');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (54, 'Egypt');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (55, 'Jordan');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (56, 'Vanuatu');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (57, 'Guam');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (58, 'Guatemala');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (59, 'Reunion');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (60, 'Rwanda');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (61, 'Micronesia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (62, 'Palau');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (63, 'Sri Lanka');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (64, 'Costa Rica');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (65, 'Gambia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (66, 'New Caledonia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (67, 'Macedonia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (68, 'Congo');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (69, 'China');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (70, 'Haiti');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (71, 'Mexico');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (72, 'Gabon');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (73, 'Swaziland');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (74, 'Tanzania');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (75, 'Monaco');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (76, 'Namibia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (77, 'Bermuda');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (78, 'Ireland');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (79, 'New Zealand');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (80, 'Saint Lucia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (81, 'Hungary');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (82, 'Kenya');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (83, 'Grenada');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (84, 'Panama');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (85, 'Niue');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (86, 'Iraq');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (87, 'Australia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (88, 'Saint Martin');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (89, 'Serbia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (90, 'Singapore');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (91, 'Ethiopia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (92, 'Romania');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (93, 'San Marino');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (94, 'Burkina Faso');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (95, 'Western Sahara');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (96, 'Saint Helena');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (97, 'Oman');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (98, 'Austria');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (99, 'Cameroon');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (100, 'Saudi Arabia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (101, 'Malta');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (102, 'Taiwan');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (103, 'Pakistan');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (104, 'Fiji');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (105, 'Liberia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (106, 'Nigeria');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (107, 'Norway');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (108, 'Slovenia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (109, 'Honduras');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (110, 'Montenegro');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (111, 'Paraguay');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (112, 'Bulgaria');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (113, 'Eritrea');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (114, 'Sao Tome and Principe');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (115, 'Wallis and Futuna');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (116, 'Croatia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (117, 'Latvia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (118, 'Antarctica (the territory South of 60 deg S)');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (119, 'Zambia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (120, 'Afghanistan');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (121, 'Holy See (Vatican City State)');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (122, 'Bouvet Island (Bouvetoya)');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (123, 'Saint Pierre and Miquelon');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (124, 'United States Virgin Islands');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (125, 'Morocco');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (126, 'Vietnam');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (127, 'Saint Barthelemy');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (128, 'British Virgin Islands');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (129, 'Tunisia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (130, 'Nepal');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (131, 'Cook Islands');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (132, 'Samoa');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (133, 'Guadeloupe');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (134, 'Aruba');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (135, 'Botswana');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (136, 'Solomon Islands');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (137, 'Jersey');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (138, 'Ecuador');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (139, 'Mayotte');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (140, 'Cyprus');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (141, 'Guinea-Bissau');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (142, 'Portugal');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (143, 'Angola');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (144, 'United States Minor Outlying Islands');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (145, 'Hong Kong');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (146, 'French Southern Territories');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (147, 'Mozambique');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (148, 'Turkey');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (149, 'Lesotho');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (150, 'Korea');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (151, 'Mauritania');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (152, 'Bolivia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (153, 'Germany');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (154, 'Equatorial Guinea');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (155, 'Cocos (Keeling) Islands');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (156, 'Madagascar');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (157, 'Puerto Rico');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (158, 'Guernsey');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (159, 'Italy');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (160, 'Japan');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (161, 'Saint Kitts and Nevis');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (162, 'Andorra');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (163, 'Jamaica');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (164, 'Tokelau');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (165, 'Svalbard & Jan Mayen Islands');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (166, 'Burundi');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (167, 'Macao');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (168, 'Denmark');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (169, 'Brunei Darussalam');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (170, 'Chad');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (171, 'Bhutan');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (172, 'Mali');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (173, 'Czech Republic');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (174, 'Bahrain');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (175, 'Moldova');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (176, 'Argentina');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (177, 'Guyana');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (178, 'Isle of Man');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (179, 'Zimbabwe');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (180, 'Iceland');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (181, 'Ghana');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (182, 'Mauritius');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (183, 'Ukraine');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (184, 'Mongolia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (185, 'Georgia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (186, 'Kyrgyz Republic');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (187, 'Armenia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (188, 'Cuba');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (189, 'Spain');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (190, 'Somalia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (191, 'Colombia');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (192, 'Dominica');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (193, 'Pitcairn Islands');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (194, 'Bahamas');
INSERT INTO `country` (`CountryID`, `Name`) VALUES (195, 'Belgium');


