#
# TABLE STRUCTURE FOR: tourreview
#

DROP TABLE IF EXISTS `tourreview`;

CREATE TABLE `tourreview` (
  `TourReviewID` int(11) NOT NULL AUTO_INCREMENT,
  `TourID` int(11) NOT NULL,
  `ReviewByUser` int(11) NOT NULL,
  `BookingID` int(11) NOT NULL,
  `Comment` text NOT NULL,
  `Rating` varchar(10) NOT NULL,
  PRIMARY KEY (`TourReviewID`),
  KEY `usertour_ibfk_1` (`TourID`),
  KEY `usertour_ibfk_2` (`ReviewByUser`),
  KEY `usertour_ibfk_3` (`BookingID`),
  CONSTRAINT `tourreview_ibfk_1` FOREIGN KEY (`ReviewByUser`) REFERENCES `user` (`UserID`) ON DELETE CASCADE,
  CONSTRAINT `usertour_ibfk_1` FOREIGN KEY (`TourID`) REFERENCES `tour` (`TourID`),
  CONSTRAINT `usertour_ibfk_3` FOREIGN KEY (`BookingID`) REFERENCES `booking` (`BookingID`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=latin1;

INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (1, 623, 3, 322, 'Maiores sit dolores odio minus esse rem nihil. Non alias magnam quos qui incidunt alias maiores eligendi. Eveniet magni quaerat est in ex ut.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (2, 318, 4, 213, 'Veniam officia hic aspernatur quas aperiam sit. Nemo cupiditate consectetur sit ea in nisi facere odio. Soluta sed eveniet sit eos laborum architecto.', '5');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (3, 733, 1, 152, 'Error at sit delectus non. Corporis aut architecto occaecati doloribus. Quia quia quia perferendis consectetur.', '5');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (4, 630, 2, 93, 'Sed qui eligendi quam et voluptatum molestiae. Dicta aut facilis perferendis id iusto. Totam illum dignissimos aut. Reiciendis vel rem omnis id ex quidem.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (5, 414, 2, 136, 'Similique vitae hic modi ea. Doloremque maiores aut saepe unde maxime. Earum voluptate quam animi voluptates et nesciunt illo.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (6, 353, 5, 652, 'Itaque nihil occaecati ea ipsam omnis dicta dolorem. Quos provident quidem quia dolore magnam. Cupiditate ab nihil eius ipsum. Provident delectus maiores similique accusamus voluptate. Vero laudantium omnis eos nesciunt fugiat quidem.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (7, 353, 2, 854, 'Dolorem eum deleniti totam non. Quidem labore qui esse voluptatum. Perspiciatis quasi autem impedit enim.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (8, 710, 4, 55, 'Saepe consequuntur atque dolores inventore est suscipit amet. Veniam aut quia pariatur voluptates temporibus maxime velit odio. Doloribus facilis error quia temporibus et aut non placeat.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (9, 707, 4, 142, 'Eum rerum veniam sequi delectus rerum. Aut officiis voluptatibus delectus inventore. Facilis inventore velit aut qui vitae.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (10, 92, 3, 36, 'Impedit eos hic voluptate sunt. Sunt aperiam voluptates repellendus sed non. Quia minima praesentium sint ut dolores esse. Quis delectus accusamus sit. Dolorem quia eligendi quibusdam dolores expedita ut est.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (11, 434, 5, 202, 'Cumque ut dolorem sequi ullam omnis odio. Vero laudantium ut laboriosam est. Placeat ea esse autem eligendi voluptatem maiores aperiam maxime.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (12, 797, 4, 57, 'Atque reiciendis doloribus ea ratione iste incidunt aliquid. Est temporibus eaque omnis sunt expedita dignissimos ab. Aut sit voluptatem recusandae aut. Exercitationem fugiat quaerat veritatis rerum in est.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (13, 10, 4, 51, 'Quisquam enim enim aut quia voluptatem. Tempore aut laborum sint est omnis excepturi. Dolor dolore architecto amet vitae nobis repellat repellendus.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (14, 418, 5, 95, 'Quia officia magnam sed eaque unde fugit. Est ullam molestiae eum aliquid nemo. Qui aliquid quia provident consectetur eum voluptates.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (15, 589, 4, 961, 'Vel odit aut et voluptas consequatur beatae explicabo et. Ipsa sit fugiat aut impedit quia sit. Inventore asperiores eligendi molestias vel perspiciatis dignissimos non. Non ut non et harum ratione ut fugiat.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (16, 595, 4, 212, 'Labore beatae eum blanditiis a nemo sed. Amet consequatur deserunt et voluptas et. Nemo quasi odio cupiditate vero.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (17, 283, 2, 912, 'Vitae nostrum consequatur ducimus nemo quo. Impedit officia at numquam nostrum ipsa. Hic neque cumque est vitae aperiam fugit perferendis omnis. Minus incidunt enim ipsa est. Impedit accusamus optio officia nisi architecto officia.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (18, 424, 1, 16, 'Quia quaerat dicta itaque. Enim quae minima perferendis tempora. Hic sed vero sit rerum et placeat beatae.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (19, 64, 3, 53, 'Itaque harum similique eveniet nihil repellat consequatur. Odit autem repellendus dolore distinctio quidem. Voluptas ut natus quasi laboriosam omnis nobis. Eaque laboriosam in sed molestiae nesciunt.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (20, 109, 5, 477, 'Molestias et impedit aut reprehenderit ducimus cumque. Voluptas perspiciatis id voluptatum sunt nihil culpa laboriosam harum. Tempora iure sequi voluptatum. Esse amet maxime culpa laborum veritatis.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (21, 189, 4, 461, 'Labore consequuntur non sit possimus reprehenderit error. Voluptatem in tenetur nesciunt veniam inventore. Omnis quidem fuga labore. Ex earum sint facere voluptatibus.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (22, 128, 5, 541, 'Voluptas veritatis minima qui error quae omnis ut. Facere quam laboriosam debitis enim. Minus nemo qui exercitationem qui voluptates et.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (23, 314, 5, 837, 'Alias tenetur repellendus ratione dolore iste dolor vero. Recusandae et ut quidem. Quis molestiae sunt ea et sed facilis est. Et ipsa quidem aliquam placeat rerum excepturi. Deserunt nam repudiandae alias praesentium praesentium consectetur.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (24, 596, 2, 21, 'Nulla beatae commodi sunt animi sit. Fuga ut quisquam quasi enim aspernatur. Quasi sint magnam impedit voluptates et quis dignissimos nihil. Ullam nihil minima accusamus nihil iure.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (25, 979, 2, 687, 'Voluptatum repellendus consequatur id numquam. Ea vitae delectus quam non quis impedit nihil. Et laborum quia beatae commodi nam consectetur. Voluptatem cum quidem nam illo molestias quia repellat et.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (26, 56, 4, 412, 'Autem enim exercitationem eos distinctio. Dolor blanditiis officiis vitae. Id incidunt dolorem perferendis voluptatem voluptates. Quas omnis doloremque illo aut blanditiis est enim. Omnis corporis quia non molestiae sed animi.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (27, 888, 4, 853, 'Provident porro tempora qui quas. Nihil rerum quas sunt occaecati perspiciatis repudiandae illum delectus. Et nisi id voluptatum voluptates.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (28, 468, 3, 898, 'Quaerat iste maiores qui. Ut ipsam deserunt non debitis. Molestiae rerum quaerat possimus quis. Similique vel voluptatibus et est laboriosam eos.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (29, 904, 2, 886, 'At minus eum molestias asperiores quaerat saepe sequi. Aut dignissimos neque placeat dolores maiores possimus.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (30, 993, 4, 493, 'Aut sunt earum iste doloremque. Omnis sed alias quo est ut eius non.', '5');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (31, 847, 4, 587, 'Vel voluptas consectetur dolorem ut ea est. Possimus impedit vitae vero quos ullam enim ut. Praesentium accusamus qui quia blanditiis occaecati qui. Error facilis atque rem libero quae omnis natus impedit.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (32, 704, 3, 130, 'Praesentium officia soluta error assumenda minus ab. At animi sed dolorem fuga qui et. Ea est tempora voluptatem mollitia.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (33, 498, 4, 128, 'Voluptatem explicabo dolores qui delectus corrupti. Facere beatae et dolores ut tenetur molestiae omnis. Porro dolore cum est possimus repudiandae. Modi error expedita culpa.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (34, 145, 3, 561, 'Sequi itaque commodi necessitatibus ullam consequatur fugit recusandae. Enim voluptas magni in qui. Placeat facere sunt est. Eaque quia assumenda sunt ut iste ipsa fuga fugiat.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (35, 180, 4, 253, 'Officia consequatur itaque sit natus veniam molestiae. Quo nihil voluptates impedit perspiciatis nostrum quis aut sit. Ut saepe rerum aspernatur asperiores architecto.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (36, 38, 3, 369, 'Qui qui itaque quia ut odit sint. Sit ipsam deserunt porro repellat in aut. Nemo similique tempore aliquid ut molestiae.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (37, 713, 2, 165, 'Qui suscipit voluptatem rerum assumenda aut magni. Officiis ipsa amet cumque possimus quibusdam. Nemo a in facere est est asperiores deleniti. Sint rem illo provident quas.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (38, 909, 4, 27, 'In voluptatem vero et quibusdam ut est aut. Magni autem voluptatem voluptas qui. Omnis perferendis ipsam veritatis ullam eaque aliquam at. Voluptatem nihil sint et. Rerum provident corporis blanditiis aliquid unde omnis nemo.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (39, 2, 4, 505, 'Rerum eum voluptatibus porro iusto quae nihil laboriosam. Accusamus vel omnis dolorem. Quaerat est aliquid dolorum ipsam quia nihil.', '5');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (40, 47, 1, 980, 'Quos incidunt corporis et placeat et optio ab. Expedita in illum doloremque ab animi. Velit ut quia totam possimus odio nulla.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (41, 191, 3, 103, 'Veritatis nam et corrupti est vel in. Aut dolor fugit quis ut consequatur ut. Tenetur molestiae eveniet ut quia labore.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (42, 392, 3, 79, 'Nemo dignissimos sapiente laboriosam optio dolorem sequi. Fugiat sint velit fugit id. Beatae at quo placeat. Quidem non fugiat amet id labore.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (43, 955, 5, 860, 'Ut a id et dolore quas officiis ad. Velit pariatur adipisci ut nobis dolor vero. Quia nobis quaerat officia est sint aut distinctio neque.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (44, 976, 2, 859, 'Iure beatae omnis et molestiae a. Eligendi dignissimos esse est reprehenderit et accusamus. Aspernatur qui molestias aut. Facilis tenetur alias sed voluptatibus consectetur earum.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (45, 745, 5, 969, 'Tempore maiores placeat et maxime aut ex. Ducimus iusto ut tempore et asperiores autem. Et illo aut qui sit quaerat temporibus vero cum.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (46, 351, 1, 592, 'Cumque ipsum aliquid quia ut non quod nihil. Sapiente ea est et debitis. Quo dignissimos minus ea dolores ut ratione dolor.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (47, 555, 1, 55, 'Qui quam quidem vero quia explicabo. Cupiditate quaerat mollitia ea soluta aut optio dolorem.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (48, 721, 5, 53, 'Omnis voluptas aperiam voluptatem. Illo doloremque quasi numquam dolore velit modi sed quae. Sit doloribus placeat quis quisquam quia cum. Nemo laboriosam esse esse quia debitis fugiat. Odit iure earum perspiciatis consequatur fugiat dolorum ea.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (49, 182, 2, 866, 'Doloremque tempora sit nam magnam ipsa. Dolor et tempore rerum provident suscipit qui. Qui a cupiditate corrupti numquam voluptates. Consequuntur ipsa at sint. Voluptatibus deleniti atque natus maiores assumenda adipisci esse.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (50, 614, 2, 362, 'Molestiae consequatur sunt est quibusdam et eligendi quo. Maiores quo et ex quaerat incidunt ullam. Provident sunt ut est molestiae sed laboriosam consequatur similique. Sapiente earum sapiente assumenda est quisquam vitae nihil voluptas. Exercitationem molestiae veritatis aspernatur.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (51, 118, 1, 651, 'Iure quos alias in veritatis. Non autem repellat ut voluptate.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (52, 730, 5, 831, 'Accusantium alias nam nihil omnis consequatur sapiente. Sed nostrum dolore eaque repudiandae quo similique eius. Non doloremque atque repudiandae eum voluptates. Atque nisi ipsum unde laborum illo doloribus consequatur expedita.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (53, 815, 5, 638, 'Quaerat deleniti ut tempore dolorem asperiores. Tempore voluptate doloribus nostrum qui incidunt et laboriosam. Nostrum sed eius animi atque consectetur.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (54, 857, 1, 816, 'Ullam magni enim qui officia voluptas. Et velit quidem eligendi et ut et unde. Rerum officiis libero et ex voluptas est tempora.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (55, 143, 3, 903, 'Odit aliquid nostrum deserunt non. Asperiores consequuntur fuga veniam molestias distinctio in.', '5');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (56, 796, 1, 333, 'Est est excepturi perferendis dignissimos voluptas. Temporibus commodi sint eum occaecati ut quidem ut. Est dignissimos praesentium tempore sint veritatis quibusdam.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (57, 6, 5, 187, 'Placeat aut ullam aut amet quibusdam. Quidem non eum fuga aut. Dignissimos consequuntur similique quibusdam aut labore voluptas.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (58, 412, 3, 961, 'Eum sed sequi pariatur aut qui fuga. Enim eligendi excepturi facilis dolore accusamus. Voluptatem eos asperiores necessitatibus doloribus possimus.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (59, 46, 2, 387, 'Eaque ipsa voluptatum architecto minima a. Fugiat nam quam optio autem. Id aliquam minus omnis qui nemo expedita.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (60, 819, 2, 791, 'Dignissimos dolorem accusantium velit vel repudiandae. Dolores possimus aut iste consectetur. Qui numquam tempora aperiam corporis eaque molestias.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (61, 355, 2, 169, 'Voluptatibus commodi maiores quaerat. Numquam necessitatibus accusantium non vero quos nostrum et ut. Voluptas eum aspernatur ipsum necessitatibus ullam.', '5');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (62, 382, 2, 910, 'Aut et officia ullam necessitatibus aperiam laudantium. Et aut harum explicabo neque accusantium aut. Culpa illum ab sunt voluptates molestiae itaque.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (63, 223, 5, 103, 'Corporis repellat incidunt modi eos sequi. Magni odio et quia error aliquam corrupti. Eius nostrum nam eum sit.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (64, 962, 1, 404, 'Delectus aperiam eius dolor dolorum. In doloremque atque numquam vel modi. Temporibus voluptatum qui cumque non commodi non natus. Magni eveniet ad velit similique.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (65, 968, 2, 575, 'Ipsum accusamus quibusdam laborum et consectetur neque. Possimus cupiditate omnis recusandae dolor. Est vel corporis nemo debitis. Consequatur perferendis voluptatem aut cum.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (66, 766, 1, 86, 'Hic quasi ut adipisci deserunt consequatur nesciunt. Esse ut vel eligendi voluptatem repellat.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (67, 226, 1, 495, 'Qui aspernatur mollitia ratione. Totam ut amet tempore ullam numquam id sint quisquam. Officiis dolorum culpa eum accusantium non.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (68, 916, 2, 41, 'Suscipit omnis ut temporibus. Aspernatur beatae eos inventore. Omnis similique ab quod rem itaque nihil voluptate excepturi.', '5');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (69, 133, 4, 772, 'Consequuntur ducimus consequatur maxime architecto debitis repellat. Fugit consequuntur debitis dolorum ut molestiae. Eius similique ut accusamus voluptatum et.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (70, 856, 1, 275, 'Vel id enim rerum placeat ut. Modi atque error officia enim magni voluptatibus ratione. Eum corporis atque dolores voluptas repudiandae. Nulla natus aut ab amet.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (71, 675, 2, 652, 'Dolorem est quasi ut qui laboriosam error distinctio. Officiis dolorem minima distinctio unde aut et esse veritatis. Et necessitatibus molestias et corrupti ab nemo.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (72, 608, 5, 680, 'Perspiciatis est quas necessitatibus quia. Consectetur quidem praesentium est voluptas voluptatibus aliquam ratione.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (73, 838, 5, 19, 'Velit recusandae similique et. Id quia qui quis neque ex et delectus. Aut atque et ut ut.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (74, 640, 2, 883, 'A culpa quos inventore ex quos facilis repellat. Sunt reiciendis sunt voluptas cumque. Quo voluptatem qui consectetur inventore debitis. Sit ullam velit quae odit molestiae quod sequi.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (75, 406, 1, 459, 'Aut molestiae recusandae vero et omnis. Cum ut alias vitae nam necessitatibus nihil. Sapiente cumque est ducimus voluptates nulla nulla cumque est.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (76, 674, 1, 760, 'Sapiente consequatur aut laboriosam delectus vel consequatur. Dolorum non at quo dolorem eum. Reprehenderit occaecati magni laborum magni.', '5');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (77, 627, 5, 55, 'Quis perspiciatis sed nesciunt quidem reprehenderit sint. Amet dolores libero consectetur. Quia qui atque aliquid sit accusamus est ipsam. Non necessitatibus autem veniam doloribus voluptatum dicta exercitationem.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (78, 670, 2, 850, 'Quia eos minima mollitia qui unde magnam. Nulla sit eos id vel numquam.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (79, 158, 5, 632, 'Sit occaecati consequatur fugiat at eveniet perspiciatis perspiciatis perspiciatis. Minima non unde repellat repellendus harum culpa autem qui. Doloribus id est sed facilis eos ratione. Provident est qui esse omnis.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (80, 254, 3, 126, 'Laboriosam dolorum vel vero hic. Ad quasi culpa cupiditate doloremque.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (81, 206, 1, 19, 'Excepturi necessitatibus in repudiandae consequuntur quas porro dolorem. Qui molestias nam cumque et eius. Unde voluptatem repellat sunt dignissimos.', '5');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (82, 211, 1, 432, 'Dolores illo atque illo voluptas delectus. Sit facilis sit ducimus. Modi consectetur facilis esse architecto sint id. Voluptatum expedita et nulla distinctio asperiores.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (83, 513, 1, 126, 'Deleniti placeat dolorum consequatur voluptas fugiat. Dolorem voluptatem quae id voluptatibus quis aut nesciunt.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (84, 472, 3, 645, 'Hic qui omnis provident eos hic dignissimos vero nostrum. Perferendis voluptatem optio ut recusandae vero quia deserunt.', '5');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (85, 897, 3, 328, 'Perspiciatis et aut ut in vero nulla nesciunt. Voluptas est molestiae fugit rerum officia. Illum et aut consequatur ratione.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (86, 920, 3, 572, 'Nobis minima id magni tempore assumenda. Aut occaecati alias non est impedit voluptates. Qui velit nulla laboriosam voluptatibus voluptatibus.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (87, 979, 2, 527, 'Temporibus accusamus quidem voluptatem voluptatem eius qui reprehenderit. Sit ipsa quidem a porro dolor aut esse accusantium. Rerum consectetur harum soluta sunt architecto.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (88, 251, 4, 816, 'Commodi fugiat suscipit laboriosam asperiores quam pariatur. Non totam quo et voluptatem rem dolore dignissimos. Suscipit rerum voluptates qui rerum consequatur. Veritatis earum animi non maiores excepturi et.', '5');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (89, 545, 1, 891, 'Est est maxime quas fugiat velit. Et ipsam itaque eligendi voluptatem sit. Iusto eveniet qui maiores velit earum quasi. Magnam aut porro assumenda at provident. Doloribus est accusantium in cumque ut.', '4');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (90, 699, 1, 950, 'Maxime veritatis maxime rem itaque. Nostrum unde quo at iure non animi atque consequatur. Sit doloremque aliquam fugiat esse id optio dignissimos. Velit ut non doloremque impedit est eius.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (91, 349, 1, 372, 'Quas placeat ducimus repudiandae quaerat qui et. Corrupti aliquam rem consequatur qui. Ratione et pariatur nemo sunt aliquid. Assumenda consequatur minus deserunt magni.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (92, 710, 3, 976, 'Est mollitia et quia. Ab aut molestiae reprehenderit nam et aut labore. Architecto asperiores temporibus odit ut in.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (93, 427, 5, 379, 'Ab quibusdam voluptatem beatae ea consequatur autem. Rerum doloremque voluptatum corrupti nihil id. Sed blanditiis quos eaque est mollitia voluptate sint corporis. Nisi quia vero quo sed.', '3');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (94, 825, 5, 584, 'In atque veniam voluptatem maxime nisi. Ratione quam at quaerat dolorum. Enim soluta quibusdam quo ut.', '2');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (95, 10, 2, 79, 'Et incidunt aut excepturi optio officia consequatur sapiente quaerat. In beatae hic sed repellat. Tenetur sunt rem alias natus sed rerum aut.', '5');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (96, 709, 4, 216, 'Libero animi eligendi fuga exercitationem blanditiis ipsam provident. Similique maxime excepturi quibusdam voluptas voluptatibus omnis. Quis laboriosam et est sequi repudiandae iure veniam.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (97, 97, 5, 920, 'Quia eos tenetur quisquam occaecati similique rerum labore. Hic enim omnis molestias est accusantium. Quo ut hic rem esse occaecati officia placeat. Ut consequatur in quis error quod magnam.', '5');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (98, 647, 5, 610, 'Accusamus ut ad magnam voluptatum dolorem alias ea. Beatae quia qui autem fugit saepe eaque repellendus. Est ab ducimus eius quia et impedit.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (99, 45, 1, 118, 'Nemo molestiae in incidunt asperiores odit sed. Tenetur iste possimus praesentium quo. Quo tempore consequatur in culpa perspiciatis dolorem praesentium. Dolorem recusandae dolores asperiores non explicabo.', '1');
INSERT INTO `tourreview` (`TourReviewID`, `TourID`, `ReviewByUser`, `BookingID`, `Comment`, `Rating`) VALUES (100, 255, 4, 942, 'Iure consequatur non odit ipsa optio similique quae. Porro assumenda eligendi perferendis corporis qui. In molestiae quidem ducimus et molestiae ducimus sed.', '2');


